---
title: "`r params$new_title`"
author: "Katrin Kulberg, Maximilian Brunner, Salomé Moret, Louis del Perugia"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params: 
  new_title: "Applied Bayesian Statistics - Spring 26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(dplyr)
library(ggplot2)
library(MASS)
library(coda)
library(MCMCpack)
library(splines)
```

## Data Preprocessing

```{r}
# loading data
load(file = "ABS_Spring26/data/speaker1_tongue_shapes.RData")
load(file = "ABS_Spring26/data/speaker2_tongue_shapes.RData")

# transforming data into a data frame shape
# first speaker
df1 <- data.frame(
  x = as.vector(speaker1[,1,]),
  y = as.vector(speaker1[,2,]),
  t = rep(1:dim(speaker1)[1], times = dim(speaker1)[3]),     # point along the curve
  shape = rep(1:dim(speaker1)[3], each = dim(speaker1)[1]),  # shape number
  speaker = 1
)

# second speaker
df2 <- data.frame(
  x = as.vector(speaker2[,1,]),
  y = as.vector(speaker2[,2,]),
  t = rep(1:dim(speaker2)[1], times = dim(speaker2)[3]),     # point along the curve
  shape = rep(1:dim(speaker2)[3], each = dim(speaker2)[1]),  # shape number
  speaker = 2
)

# reordering the indices t for speaker 2
df2$t <- 45 - df2$t + 1

# given that the 5th shape was already in the right order, reordering that shape again
# additionally removing an outlier from shape 5
df2 <- df2 %>%
  mutate(t= ifelse(shape == 5, 45 - t + 1, t)) %>% 
  filter(!(shape == 5 & t == 45))


# adding standardised index t to both data frames
# (multiplying by 1/(n+1))
df1$t_standardised <- df1$t / 66
df2$t_standardised <- df2$t / 46

```

## Descriptive Overview

```{r}
# FULL CURVES

# curves of speaker 1
ggplot(df1, aes(x = x, y = y, group = t)) +
  geom_point(size = 1) +                       
  facet_wrap(~shape, ncol = 5) +      
  coord_fixed() +                     
  theme_bw() +
  labs(title = "Speaker 1: 2D Tongue Shapes", 
       subtitle = "Shapes 1 and 2 are partially observed",
       x = "X Coordinate", y = "Y Coordinate")

# curves of speaker 2
ggplot(df2, aes(x = x, y = y, group = t)) +
  geom_point(size = 1) +                       
  facet_wrap(~shape, ncol = 5) +      
  coord_fixed() +                     
  theme_bw() +
  labs(title = "Speaker 2: 2D Tongue Shapes", 
       subtitle = "Shapes 1 and 2 are partially observed",
       x = "X Coordinate", y = "Y Coordinate")

# MARGINAL CURVES

# speaker 1, x curve
ggplot(df1, aes(x = t, y = x, group = t)) +
  geom_point(size = 1) +                       
  facet_wrap(~shape, ncol = 5) +      
  coord_fixed() +                     
  theme_bw() +
  labs(title = "Speaker 1: Marginal Curves for X-Coordinate", 
       x = "Normalized Arc-length (t)", y = "X Coordinate")

# speaker 1, y curve
ggplot(df1, aes(x = t, y = y, group = t)) +
  geom_point(size = 1) +                       
  facet_wrap(~shape, ncol = 5) +      
  coord_fixed() +                     
  theme_bw() +
  labs(title = "Speaker 1: Marginal Curves for Y-Coordinate", 
       x = "Normalized Arc-length (t)", y = "Y Coordinate")

# speaker 2, x curve
ggplot(df2, aes(x = t, y = x, group = t)) +
  geom_point(size = 1) +                       
  facet_wrap(~shape, ncol = 5) +      
  coord_fixed() +                     
  theme_bw() +
  labs(title = "Speaker 2: Marginal Curves for X-Coordinate", 
       x = "Normalized Arc-length (t)", y = "X Coordinate")

# speaker 2, y curve
ggplot(df2, aes(x = t, y = y, group = t)) +
  geom_point(size = 1) +                       
  facet_wrap(~shape, ncol = 5) +      
  coord_fixed() +                     
  theme_bw() +
  labs(title = "Speaker 2: Marginal Curves for Y-Coordinate", 
       x = "Normalized Arc-length (t)", y = "Y Coordinate")
```

# Function Definitions

```{r}

# function that, for given x and y, calculates coefficients for the polynomial basis for a given degree
coefs <- function(x, y, degree){
  
  # design matrix
  X_poly <- sapply(0:degree, function(i) x^i)
  # finding coefficients
  model <- lm(y ~ X_poly - 1)
  beta <- coef(model)
  
  return(beta)
}

# function that computes coefficients for the fully observed curves
# data frame, variable and degree can be specified
compute_betas <- function(df, variable, degree, shapes = 3:10) {
  
  betas_list <- lapply(shapes, function(i) {
    
    # selecting response
    y <- df[df$shape == i, variable]
    
    # based on standardised index t
    coefs(df[df$shape == i, "t_standardised"], y, degree)
  })
  
  do.call(rbind, betas_list)
}

# function that selects the best fitting curves based on observed data
# number of curves can be specified
# looks at a partially observed tongue shape, compares it against a library of curves (derived from df), and picks the ones that fit the observed points the best
curve_selection <- function(X_observed, y_observed, number = 6){
  
  results <- matrix(NA, nrow = ncol(X_observed), ncol = 2)
  
  for (i in 1:ncol(X_observed)){
    
    # similarity is based on squared difference
    similarity <- sum((X_observed[,i] - y_observed)^2)
    results[i,1] <- i
    results[i,2] <- similarity
  }
  
  # sorting by similarity in an ascending order
  results <- results[order(results[,2]), ]
  
  # returning indices
  return(results[1:number,1])
  
}

# function for Gibbs sampling in case of modelling x and y curves separately
Gibbs_1d <- function(x, y, coefs, observed, simulations){
  
  # for testing purposes
  #x <- subset(df1, shape == 1)$t_standardised
  #coefs <- coefs_X
  #observed <- 21:65
  #y <- subset(df1, shape == 1)$x
  #simulations <- 5000
  
  # building design matrix
  X_poly <- sapply(0:(ncol(coefs)-1), function(i) x^i)
  X_full <- t((coefs) %*% t(X_poly))
  
  # choosing the observed parts
  y_observed <- y[observed]
  X_observed <- X_full[observed, ]
  
  # curve selection
  selected <- curve_selection(X_observed, y_observed, ncol(coefs))
  X_observed <- X_observed[, selected]
  X_full <- X_full[,selected]
  
  
  # initialising parameters for priors
  p <- ncol(X_observed)
  beta0 <- rep(0.5, p)
  Sigma0_inv <- 1/1* diag(1,p)
  n <- length(y_observed)
  
  # choose 
  nu0 <- 2
  s20 <- 5
  
  beta_samples <- matrix(NA, nrow=simulations, ncol=p)
  sigma2_samples <- numeric(simulations)
  
  # setting initial values
  beta_samples[1, ] <- rep(1/p, p)
  sigma2_samples[1] <- var(y_observed)
  n <- length(y_observed)
  
  for(iter in 2:simulations){
    
    # update beta
    # finding covariance matrix
    V_beta <- solve(t(X_observed) %*% X_observed / sigma2_samples[iter-1] + Sigma0_inv)
    # find mean vectors
    m_beta <- V_beta %*% (t(X_observed) %*% y_observed / sigma2_samples[iter-1] + Sigma0_inv %*% beta0)
    
    # sampling
    #beta_samples[iter, ] <- m_beta + t(chol(V_beta)) %*% rnorm(p)
    beta_samples[iter, ] <- mvrnorm(1, mu = m_beta, Sigma = V_beta)
    # updating sigma^2
    
    # calculating SSR
    SSR <- sum((y_observed - X_observed %*% beta_samples[iter, ])^2)

    # parameters for inverse gamma
    shape_sig <- (nu0 + n) / 2
    rate_sig  <- (nu0 * s20 + SSR) / 2
    
    # sampling
    sigma2_samples[iter] <- 1 / rgamma(1, shape = shape_sig, rate = rate_sig)
  }
  
  # predictions for the full curve
  predictions <- X_full %*% t(beta_samples)
  
  # returning predictions, betas and selected curves
  return(list(
    predictions = predictions,
    beta_samples = beta_samples,
    selected = selected
  ))
  
}

# function for Gibbs sampling in case of modelling x and y curves together
Gibbs_2d <- function(points, x, y, coefs_X, coefs_Y, observed, simulations){
  
  # for testing purposes
  
  #points <- subset(df1, shape == 1)$t_standardised
  #points <- 1:65
  #coefs_X <- coefs_X_speaker1
  #coefs_Y <- coefs_Y_speaker1
  #observed <- c(1:19, 41:65)
  #observed <- 21:65
  #x <- subset(df1, shape == 1)$x
  #y <- subset(df1, shape == 1)$y
  #simulations <- 5000
  
  # building design matrix for x and y
  X_poly_x <- sapply(0:(ncol(coefs_X)-1), function(i) points^i)
  X_poly_y <- sapply(0:(ncol(coefs_Y)-1), function(i) points^i)
  X_full_x <- t((coefs_X) %*% t(X_poly_x))
  X_full_y <- t((coefs_Y) %*% t(X_poly_y))
  
  # combining x and y
  X_full <- rbind(X_full_x,  X_full_y)
  
  # choosing the observed parts for both
  X_observed_x <- X_full_x[observed,]
  X_observed_y <- X_full_y[observed,]
  y_observed_x <- x[observed]
  y_observed_y <- y[observed]
  
  # combining the observed parts
  y_observed <- c(y_observed_x, y_observed_y)
  X_observed <- rbind(X_observed_x, X_observed_y)
  
  # curve selection (11 curves)
  selected <- curve_selection(X_observed, y_observed, (ncol(coefs_X) + ncol(coefs_Y)))
  X_observed <- X_observed[, selected]
  X_full <- X_full[,selected]
  
  
  # initialising parameters for priors
  p <- ncol(X_observed)
  beta0 <- rep(0.5, p)
  Sigma0_inv <- 1/1* diag(1,p)

  # choose 
  nu0 <- 2*2
  s20 <- 5*2.5
  n <- length(y_observed)
  
  beta_samples <- matrix(NA, nrow=simulations, ncol=p)
  sigma2_samples <- numeric(simulations)
  
  # initial values
  beta_samples[1, ] <- rep(1/p, p)
  sigma2_samples[1] <- var(y_observed)
  
  for(iter in 2:simulations){
    
    # updating beta
    # finding covariance matrix
    V_beta <- solve((t(X_observed) %*% X_observed) / sigma2_samples[iter-1] + Sigma0_inv)
    
    # finding mean vectors
    m_beta <- V_beta %*% ((t(X_observed) %*% y_observed) / sigma2_samples[iter-1] + Sigma0_inv %*% beta0)
    
    # sampling beta
    #beta_samples[iter, ] <- m_beta + t(chol(V_beta)) %*% rnorm(p)
    beta_samples[iter, ] <- mvrnorm(1, mu = m_beta, Sigma = V_beta)
    
    # updating sigma^2
    
    # SSR
    SSR <- sum((y_observed - X_observed %*% beta_samples[iter, ])^2)
    
    # parameters for inverse gamma
    shape_sig <- (nu0 + n) / 2
    rate_sig  <- (nu0 * s20 + SSR) / 2
    
    # sampling
    sigma2_samples[iter] <- 1 / rgamma(1, shape = shape_sig, rate = rate_sig)
  }
  
  # predictions for the full curve
  predictions <- X_full %*% t(beta_samples)
  
  # returning predictions, betas and selected curves
  return(list(
    predictions = predictions,
    beta_samples = beta_samples,
    selected = selected
  ))
  
}

# function that plots the curve with credible interval in 1D (Base R)
summarise_results_1d <- function(predictions, points, true_data){
  
  # Calculate quantiles
  best_estimate <- apply(predictions, 1, quantile, probs = 0.5)
  lower_95 <- apply(predictions, 1, quantile, probs = 0.025)
  upper_95 <- apply(predictions, 1, quantile, probs = 0.975)
  
  # Determine axis limits dynamically
  y_lim <- range(c(lower_95, upper_95, true_data), na.rm = TRUE)
  
  # Set academic graphical parameters
  # Save original parameters to restore later
  old_par <- par(family = "serif", bty = "l", las = 1, mar = c(5, 5, 4, 2) + 0.1)
  
  # Initialize plot
  plot(points, best_estimate, type = "n", ylim = y_lim,
       xlab = expression(paste("Normalized Arc-length ", italic(t))),
       ylab = expression(paste("Coordinate ", italic(x))),
       main = "1D Curve Reconstruction",
       cex.main = 1.2, cex.lab = 1.1)
  
  # Add 95% Credible Interval (shaded polygon)
  polygon(x = c(points, rev(points)), 
          y = c(lower_95, rev(upper_95)), 
          col = rgb(0.5, 0.5, 0.5, alpha = 0.3), border = NA)
  
  # Add best estimate line
  lines(points, best_estimate, col = "black", lwd = 2)
  
  # Add observed data securely
  valid_idx <- which(!is.na(true_data))
  points(points[valid_idx], true_data[valid_idx], 
         pch = 21, bg = "red", col = "white", cex = 1.2)
  
  # Add legend
  legend("topleft", 
         legend = c("Posterior Median", "95% Credible Interval", "Observed Data"),
         lwd = c(2, NA, NA), pch = c(NA, 15, 21), 
         pt.bg = c(NA, rgb(0.5, 0.5, 0.5, alpha = 0.3), "red"),
         col = c("black", rgb(0.5, 0.5, 0.5, alpha = 0.3), "white"),
         bty = "n")
  
  # Restore original parameters
  par(old_par)
}

# function that plots the curve with credible interval in 2D (Base R)
summarise_results_2d <- function(predictions_x, predictions_y, points, true_data_x, true_data_y){
  
  # Calculate quantiles for X
  best_x <- apply(predictions_x, 1, quantile, probs = 0.5)
  low_x <- apply(predictions_x, 1, quantile, probs = 0.025)
  up_x <- apply(predictions_x, 1, quantile, probs = 0.975)
  
  # Calculate quantiles for Y
  best_y <- apply(predictions_y, 1, quantile, probs = 0.5)
  low_y <- apply(predictions_y, 1, quantile, probs = 0.025)
  up_y <- apply(predictions_y, 1, quantile, probs = 0.975)
  
  # Determine axis limits dynamically
  x_lim <- range(c(low_x, up_x, true_data_x), na.rm = TRUE)
  y_lim <- range(c(low_y, up_y, true_data_y), na.rm = TRUE)
  
  # Set academic graphical parameters
  old_par <- par(family = "serif", bty = "l", las = 1, mar = c(5, 5, 4, 2) + 0.1)
  
  # Initialize plot
  plot(best_x, best_y, type = "n", xlim = x_lim, ylim = y_lim,
       xlab = expression(paste("Spatial Coordinate ", italic(x))),
       ylab = expression(paste("Spatial Coordinate ", italic(y))),
       main = "2D Tongue Shape Reconstruction",
       cex.main = 1.2, cex.lab = 1.1)
  
  # Add 2D Credible Intervals (Base R equivalent of geom_rect)
  # This plots a semi-transparent rectangle for each point's independent uncertainty
  rect(xleft = low_x, ybottom = low_y, xright = up_x, ytop = up_y,
       col = rgb(0.5, 0.5, 0.5, alpha = 0.3), border = NA)
  
  # Add mean curve
  lines(best_x, best_y, col = "black", lwd = 2)
  
  # Add observed data securely
  valid_idx <- which(!is.na(true_data_x) & !is.na(true_data_y))
  points(true_data_x[valid_idx], true_data_y[valid_idx], 
         pch = 21, bg = "red", col = "red", cex = 1.2)
         
  # Add legend
  legend("topleft", 
         legend = c("Posterior Median Curve", "Marginal 95% CI Bounds", "Observed Points"),
         lwd = c(2, NA, NA), pch = c(NA, 15, 21), 
         pt.bg = c(NA, rgb(0.5, 0.5, 0.5, alpha = 0.3), "red"),
         col = c("black", NA, "black"),
         bty = "n")
         
  # Restore original parameters
  par(old_par)
}

```


# Conjugate model (example)

```{r}
# without sampling sigma^2
# could be done for both 1D and 2D.
# as an example, here is for 1D, speaker 1, x

# setting degrees
degree_x <- 5
degree_y <- 4

coefs_X_speaker1 <- compute_betas(df1, "x", degree_x)
coefs_Y_speaker1 <- compute_betas(df1, "y", degree_y)

coefs_X_speaker2 <- compute_betas(df2, "x", degree_x)
coefs_Y_speaker2 <- compute_betas(df2, "y", degree_y)

######################################################

conjugate_model_1d <- function(x, y, coefs, observed, samples){
  
  X_poly <- sapply(0:(ncol(coefs)-1), function(i) x^i)
  X_full <- t((coefs) %*% t(X_poly))
  
  y_observed <- y[observed]
  X_observed <- X_full[observed, ]
  
  # curve selection
  selected <- curve_selection(X_observed, y_observed, ncol(coefs))
  X_observed <- X_observed[, selected]
  X_full <- X_full[,selected]

  # initialising parameters for priors
  p <- ncol(X_observed)
  # priors
  beta0 <- rep(0.5, p)
  Sigma0_inv <- 1/0.5* diag(1,p)
  sigma2 <- 2 # FIXED! really depends on this; this can be investigated further which choice makes the most sense
  n <- length(y_observed)
  
  # calculating covariance and mean
  V_beta <- solve(t(X_observed) %*% X_observed / sigma2 + Sigma0_inv)
  m_beta <- V_beta %*% (t(X_observed) %*% y_observed / sigma2 + Sigma0_inv %*% beta0)
  
  # sampling
  beta_samples <- mvrnorm(samples, mu = m_beta, Sigma = V_beta)
  
  predictions <- X_full %*% t(beta_samples)
    
  return(predictions)
}


curve_1x_speaker1 <- conjugate_model_1d(subset(df1, shape == 1)$t_standardised, subset(df1, shape == 1)$x,  coefs_X_speaker1, 21:65, 5000)
summarise_results_1d(curve_1x_speaker1, 1:65, subset(df1, shape == 1)$x)



```


# 1D approaches

```{r}
# modelling x and y curves separately

# setting degrees
degree_x <- 5
degree_y <- 4

coefs_X_speaker1 <- compute_betas(df1, "x", degree_x)
coefs_Y_speaker1 <- compute_betas(df1, "y", degree_y)

coefs_X_speaker2 <- compute_betas(df2, "x", degree_x)
coefs_Y_speaker2 <- compute_betas(df2, "y", degree_y)

#####################################################

# Gibbs sampling procedures
# SPEAKER 1
# observed portion for curve 1: 21:65
# observed portion for curve 2: c(1:19, 41:65) 
speaker_1_shape_1_x <- Gibbs_1d(subset(df1, shape == 1)$t_standardised, subset(df1, shape == 1)$x, coefs_X_speaker1, 21:65, 5000)
summarise_results_1d(speaker_1_shape_1_x$predictions, 1:65, subset(df1, shape == 1)$x)

speaker_1_shape_1_y <- Gibbs_1d(subset(df1, shape == 1)$t_standardised, subset(df1, shape == 1)$y, coefs_Y_speaker1, 21:65, 5000)
summarise_results_1d(speaker_1_shape_1_y$predictions, 1:65, subset(df1, shape == 1)$y)

# 2d visualisation
summarise_results_2d(speaker_1_shape_1_x$predictions, speaker_1_shape_1_y$predictions, 1:65, subset(df1, shape == 1)$x, subset(df1, shape == 1)$y)

speaker_1_shape_2_x <- Gibbs_1d(subset(df1, shape == 2)$t_standardised, subset(df1, shape == 2)$x, coefs_X_speaker1, c(1:19, 41:65), 5000)
summarise_results_1d(speaker_1_shape_2_x$predictions, 1:65, subset(df1, shape == 2)$x)


speaker_1_shape_2_y <- Gibbs_1d(subset(df1, shape == 2)$t_standardised, subset(df1, shape == 2)$y, coefs_Y_speaker1, c(1:19, 41:65), 5000)
summarise_results_1d(speaker_1_shape_2_y$predictions, 1:65, subset(df1, shape == 2)$y)


# SPEAKER 2
# observed portion for curve 1: 21:45
# observed portion for curve 2: c(1:19, 36:45)

speaker_2_shape_1_x <- Gibbs_1d(subset(df2, shape == 1)$t_standardised, subset(df2, shape == 1)$x, coefs_X_speaker2, 21:45, 5000)
summarise_results_1d(speaker_2_shape_1_x$predictions, rev(1:45), subset(df2, shape == 1)$x)


speaker_2_shape_1_y <- Gibbs_1d(subset(df2, shape == 1)$t_standardised, subset(df2, shape == 1)$y, coefs_Y_speaker2, 21:45, 5000)
summarise_results_1d(speaker_2_shape_1_y$predictions, rev(1:45), subset(df2, shape == 1)$y)

summarise_results_2d(speaker_2_shape_1_x$predictions, speaker_2_shape_1_y$predictions, rev(1:65), subset(df2, shape == 1)$x, subset(df2, shape == 1)$y)


speaker_2_shape_2_x <- Gibbs_1d(subset(df2, shape == 2)$t_standardised, subset(df2, shape == 2)$x, coefs_X_speaker2, c(1:19, 36:45), 5000)
summarise_results_1d(speaker_2_shape_2_x$predictions, rev(1:45), subset(df2, shape == 2)$x)


speaker_2_shape_2_y <- Gibbs_1d(subset(df2, shape == 2)$t_standardised, subset(df2, shape == 2)$y, coefs_Y_speaker2, c(1:19, 36:45), 5000)
summarise_results_1d(speaker_2_shape_2_y$predictions, rev(1:45), subset(df2, shape == 2)$y)


```


# 2D approaches

```{r}
# modelling x and y curves together
# note that here we allow to select from both speaker 1 and speaker 2
# that is because we need 11 curves (6+5 parameters in total)

# setting degrees
degree_x <- 5
degree_y <- 4

coefs_X_speaker1 <- compute_betas(df1, "x", degree_x)
coefs_Y_speaker1 <- compute_betas(df1, "y", degree_y)

coefs_X_speaker2 <- compute_betas(df2, "x", degree_x)
coefs_Y_speaker2 <- compute_betas(df2, "y", degree_y)


# combining information from speaker 1 and 2
coefs_X <- rbind(coefs_X_speaker1, coefs_X_speaker2)
coefs_Y <- rbind(coefs_Y_speaker1, coefs_Y_speaker2)

#######################################################
# Gibbs sampling procedures
# SPEAKER 1
# observed portion for curve 1: 21:65
# observed portion for curve 2: c(1:19, 41:65)

speaker1_curve1 <- Gibbs_2d(subset(df1, shape == 1)$t_standardised, subset(df1, shape == 1)$x, subset(df1, shape == 1)$y, coefs_X, coefs_Y, 21:65, simulations=5000)

summarise_results_1d(speaker1_curve1$predictions[1:65,], 1:65, subset(df1, shape == 1)$x)

summarise_results_2d(speaker1_curve1$predictions[1:65,], speaker1_curve1$predictions[66:130,], 1:65, subset(df1, shape == 1)$x, subset(df1, shape == 1)$y)

speaker1_curve2 <- Gibbs_2d(subset(df1, shape == 2)$t_standardised, subset(df1, shape == 2)$x, subset(df1, shape == 2)$y, coefs_X, coefs_Y, c(1:19, 41:65), simulations=5000)

summarise_results_1d(speaker1_curve2$predictions[1:65,], 1:65, subset(df1, shape == 2)$x)

summarise_results_2d(speaker1_curve2$predictions[1:65,], speaker1_curve2$predictions[66:130,], 1:65, subset(df1, shape == 2)$x, subset(df1, shape == 2)$y)

# SPEAKER 2
# observed portion for curve 1: 21:45
# observed portion for curve 2: c(1:19, 36:45)

speaker2_curve1 <- Gibbs_2d(subset(df2, shape == 1)$t_standardised, subset(df2, shape == 1)$x, subset(df2, shape == 1)$y, coefs_X, coefs_Y, 21:45, simulations=5000)

summarise_results_1d(speaker2_curve1$predictions[1:45,], rev(1:45), subset(df2, shape == 1)$x)

summarise_results_2d(speaker2_curve1$predictions[1:45,], speaker2_curve1$predictions[46:90,], 1:45, subset(df2, shape == 1)$x, subset(df2, shape == 1)$y)


speaker2_curve2 <- Gibbs_2d(subset(df2, shape == 2)$t_standardised, subset(df2, shape == 2)$x, subset(df2, shape == 2)$y, coefs_X, coefs_Y, c(1:19, 36:45), simulations=5000)

summarise_results_2d(speaker2_curve2$predictions[1:45,], speaker2_curve2$predictions[46:90,], 1:45, subset(df2, shape == 2)$x, subset(df2, shape == 2)$y)


```

# Diagnostics MCMC
```{r}
# Let us define our diagnostics MCMC function
mcmc_diag <- function(Gibbs_Output, burnin){
  # First, extract the samples matrice
  beta_samples <- as.matrix(Gibbs_Output$beta_samples)
  
  # Store the dimensions, S is the number of iterations, P the number of parameters
  S <- nrow(beta_samples)
  p <- ncol(beta_samples)
  
  # Check that burn-in is smaller than the number of iterations
  if (burnin >= S){
    stop("The burnin (", burnin, "is bigger than the total number of samples", S)
  }
  
  # Now, apply the burn-in
  beta_sampclean <- beta_samples[(burnin+1):S, ,drop=FALSE]
  
  # TRACEPLOT:
  # Let's do a Traceplot for each beta to check the MCMC
  param_names <- paste0("Beta_", 1:p) # Will be used for the name of traceplot
  # Just to be readable, we put 3 graphs per row.
  n_rowgraph <- ceiling(p/3)
  n_colgraph <- 3 
  par(mfrow = c(n_rowgraph, n_colgraph))
  
  for (j in 1:p){ # for each parameter
    plot(1:S, beta_samples[,j], type="l", main = paste("Traceplot of", param_names[j]), xlab = "iterations", ylab = "value of beta", col = "blue1")
    abline(v = burnin, col = "red2", lty = 2) # Add a vertical line at the burn-in
  }

  
  # AUTOCORRELATION FUNCTION:
  # Now, let's plot the autocorrelation functions
  for (j in 1:p){
    acf(beta_sampclean[,j], main = paste("ACF of", param_names[j]), lag.max = 50, cex.main = 0.9)
  }
  
  # EFFECTIVE SAMPLE SIZE
  # We use the coda package, but first we have to convert beta_sampclean into an mcmc object
  beta_mcmc <- as.mcmc(beta_sampclean)
  colnames(beta_mcmc) <- param_names
  
  # Now, we can compute the effective sample size for each parameter
  ess <- effectiveSize(beta_mcmc)
  print(paste("Minimum ESS", min(ess)))
  print(paste("Mean ESS", mean(ess)))
  print(round(ess, 1))
  
  # Return invisibly a list of ess and corresponding beat_sampclean
  invisible(list(ess = ess, beta_sampclean = beta_sampclean))
}
```

# Cell to see the output !
```{r}
speaker_1_shape_1_x <- Gibbs_1d(
  subset(df1, shape == 1)$t_standardised,
  subset(df1, shape == 1)$x,
  coefs_X_speaker1, 21:65, 5000
)

res <- mcmc_diag(speaker_1_shape_1_x, 500)
res$ess
```

=======
# 1D HLM approach
```{r}
# fitting hlm with b-splines + gibbs
# y_j | beta_j, sig2 ~ N(X_j * beta_j, sig2 * I)
# beta_j | theta, Sigma ~ N(theta, Sigma)

hlm_with_bspline_gibbs <- function(dataframe, df = 6, Ngibbs = 5000, target_var = "x") {
  tictoc::tic()
  # sort by shape & time first, otherwise the splines get messed up
  dataframe <- dataframe[order(dataframe$shape, dataframe$t), ]
  shapes <- unique(dataframe$shape)
  m <- length(shapes)
  
  Y <- list()
  X <- list()
  N <- numeric(m)
  
  n_points <- max(dataframe$t, na.rm = TRUE)
  full_points <- 1:n_points
  
  # using cubic splines (degree 3) - this acts as our smooth "wire" to connect the dots
  X_full <- bs(full_points, df = df, degree = 3, intercept = TRUE)
  p <- ncol(X_full)
  
  for (j in 1:m) {
    shape_data <- subset(dataframe, shape == shapes[j])
    
    # drop missing values for the likelihood update
    obs_data <- na.omit(shape_data[[target_var]]) 
    obs_idx <- which(!is.na(shape_data[[target_var]]))
    
    Y[[j]] <- obs_data
    X[[j]] <- X_full[obs_idx, , drop = FALSE] # design matrix only for observed times
    N[j] <- length(obs_data)
  }
  
  # --- priors ---
  
  # theta ~ N(mu0, Lambda0_inv^-1)
  # diffuse prior for the mean template so the data takes over
  mu0 <- rep(0, p) 
  Lambda0_inv <- diag(1/100, p) 
  
  # Sigma ~ Inv_Wishart(eta0, S0)
  eta0 <- p + 2 
  S0 <- diag(1, p) 
  
  # sig2 ~ InvGamma
  nu0 <- 1
  
  # empirical bayes trick: initialize sig2 with pooled variance to keep the chain stable
  sig20 <- var(unlist(Y), na.rm = TRUE)
  if(is.na(sig20) || sig20 == 0) sig20 <- 1
  
  # --- initizalise MCMC
  theta <- mu0
  Sigma <- S0
  inv_Sigma <- solve(Sigma)
  sig2 <- sig20
  
  BETA <- matrix(0, nrow = m, ncol = p)
  theta_samples <- matrix(NA, nrow = Ngibbs, ncol = p)
  
  # track SSR for diagnostics
  ssr_samples <- numeric(Ngibbs)
  all_pred_samples <- lapply(1:m, function(x) matrix(NA, nrow = Ngibbs, ncol = n_points))
  names(all_pred_samples) <- as.character(shapes) 
  
  # --- gibbs
  for (iter in 1:Ngibbs) {
    
    # 1. update beta_j (shape specific coefs)
    # standard conjugate update - precisions add up (prior + data)
    for (j in 1:m) {
      Vj <- solve(inv_Sigma + (t(X[[j]]) %*% X[[j]]) / sig2)
      Ej <- Vj %*% (inv_Sigma %*% theta + (t(X[[j]]) %*% Y[[j]]) / sig2) 
      BETA[j, ] <- mvrnorm(1, mu = Ej, Sigma = Vj) #sample betas
    }
    
    # 2. update theta (population average shape)
    # pool info across all shapes to figure out the master template
    Lm <- solve(Lambda0_inv + m * inv_Sigma) 
    mum <- Lm %*% (Lambda0_inv %*% mu0 + inv_Sigma %*% colSums(BETA))
    theta <- as.vector(mvrnorm(1, mu = mum, Sigma = Lm)) #sample thetas
    
    # 3. update Sigma (between-shape cov matrix)
    # calculate scatter matrix (deviations from the average)
    # this dictates the shrinkage: smaller sigma => stronger pull toward theta
    S_theta <- matrix(0, p, p)
    for (j in 1:m) {
      diff <- BETA[j, ] - theta
      S_theta <- S_theta + (diff %*% t(diff))
    }
    Sigma <- riwish(v = eta0 + m, S = S0 + S_theta) #sample sigma
    inv_Sigma <- solve(Sigma) # precompute for the next loop
    
    # 4. update sig2 and get predictions
    # assuming homoscedasticity here (one global variance)
    SSR <- 0
    for (j in 1:m) {
      shape_residuals <- Y[[j]] - X[[j]] %*% BETA[j, ]
      SSR <- SSR + sum(shape_residuals^2)
      
      # map coefs through full spline matrix to predict missing segments
      all_pred_samples[[j]][iter, ] <- X_full %*% BETA[j, ]
    }
    
    ssr_samples[iter] <- SSR 
    
    shape_sig <- (nu0 + sum(N)) / 2
    rate_sig  <- (nu0 * sig20 + SSR) / 2
    sig2 <- 1 / rgamma(1, shape = shape_sig, rate = rate_sig) # 1/rgamma = InvGamma
    
    theta_samples[iter, ] <- theta
  }
  tictoc::toc()
  return(list(
    theta_samples = theta_samples, 
    all_predictions = all_pred_samples, 
    ssr_samples = ssr_samples
  ))
}

###### main
run_main <- function(dataset, dataset_name = "Data", shapes_to_plot = c(1, 2), burn_in = 1000) {
  
  cat("---\nrunning dataset:", dataset_name, "\n---\n")
  
  dataset <- dataset[order(dataset$shape, dataset$t), ]
  n_points <- max(dataset$t, na.rm = TRUE)
  full_points <- 1:n_points
  
  # fit marginals ->> we run x and y independently here - ignores x and y covariance but works as a baseline (fPCA??)
  cat("fitting x model...\n")
  hm_results_x <- hlm_with_bspline_gibbs(dataset, df = 6, Ngibbs = 5000, target_var = "x")
  
  cat("fitting y model...\n")
  hm_results_y <- hlm_with_bspline_gibbs(dataset, df = 6, Ngibbs = 5000, target_var = "y")
  
  # check global fit
  mean_ssr_x <- mean(hm_results_x$ssr_samples[-(1:burn_in)])
  mean_ssr_y <- mean(hm_results_y$ssr_samples[-(1:burn_in)])
  cat("\n--- model fit ---\n")
  cat(sprintf("mean ssr (x): %.4f\n", mean_ssr_x))
  cat(sprintf("mean ssr (y): %.4f\n\n", mean_ssr_y))
  
  plot_traces(hm_results_x$theta_samples, burn_in, var_name = paste(dataset_name, "- Global X"))
  plot_traces(hm_results_y$theta_samples, burn_in, var_name = paste(dataset_name, "- Global Y"))
  
  # extract and plot targets
  for (target_shape_id in shapes_to_plot) {
    cat(sprintf("reconstructing shape %d...\n", target_shape_id))
    
    shape_data <- subset(dataset, shape == target_shape_id)
    shape_char <- as.character(target_shape_id)
    
    preds_x <- hm_results_x$all_predictions[[shape_char]]
    preds_y <- hm_results_y$all_predictions[[shape_char]]
    
    # local rmse
    post_mean_x <- colMeans(preds_x[-(1:burn_in), ])
    post_mean_y <- colMeans(preds_y[-(1:burn_in), ])
    
    obs_idx_x <- which(!is.na(shape_data$x))
    obs_idx_y <- which(!is.na(shape_data$y))
    
    rmse_x <- sqrt(mean((shape_data$x[obs_idx_x] - post_mean_x[obs_idx_x])^2))
    rmse_y <- sqrt(mean((shape_data$y[obs_idx_y] - post_mean_y[obs_idx_y])^2))
    
    cat(sprintf("  rmse -> x: %.4f | y: %.4f\n", rmse_x, rmse_y))
    
    plot_1d_reconstruction(preds_x, burn_in, 
                           observed_data = shape_data$x, 
                           observed_t = shape_data$t, 
                           full_points = full_points, 
                           var_name = paste(dataset_name, "Shape", target_shape_id, "- X"))
    
    plot_1d_reconstruction(preds_y, burn_in, 
                           observed_data = shape_data$y, 
                           observed_t = shape_data$t, 
                           full_points = full_points, 
                           var_name = paste(dataset_name, "Shape", target_shape_id, "- Y"))
    
    plot_2d_reconstruction(samples_x = preds_x,
                           samples_y = preds_y,
                           burn_in = burn_in,
                           obs_x = shape_data$x, 
                           obs_y = shape_data$y)
  }
  cat("done.\n\n")
}

#run for speaker 1 and 2
run_main(dataset = df1, dataset_name = "df1", shapes_to_plot = c(1, 2))
run_main(dataset = df2, dataset_name = "df2", shapes_to_plot = c(1, 2))
```
